# Generated by Django 4.2.27 on 2025-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="numero_documento",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                verbose_name="N° Factura / Boleta",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("sin_doc", "Sin documento"),
                    ("boleta", "Boleta"),
                    ("factura", "Factura"),
                ],
                db_index=True,
                default="sin_doc",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero_documento", ""), _negated=True),
                fields=("tipo_documento", "numero_documento"),
                name="uniq_tipo_numero_documento",
            ),
        ),
    ]
