# Generated by Django 4.2.27 on 2025-12-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_venta_numero_documento_venta_tipo_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="venta",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
    ]
