# Generated by Django 4.2.27 on 2025-12-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_cliente_observaciones_venta_observaciones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("sin_doc", "Sin documento"),
                    ("boleta", "Boleta"),
                    ("factura", "Factura"),
                    ("nota_credito", "Nota de crédito"),
                ],
                db_index=True,
                default="sin_doc",
                max_length=20,
            ),
        ),
    ]
