# Generated by Django 4.2.27 on 2025-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_venta_tipo_documento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="total",
            new_name="kilos_total",
        ),
        migrations.AddField(
            model_name="venta",
            name="monto_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="venta",
            name="numero_documento",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                verbose_name="N° Factura / Boleta / Nota Crédito",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("sin_doc", "Sin documento"),
                    ("boleta", "Boleta"),
                    ("factura", "Factura"),
                    ("nota_credito", "Nota crédito"),
                ],
                db_index=True,
                default="sin_doc",
                max_length=20,
            ),
        ),
    ]
