# Generated by Django 4.2.27 on 2025-12-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_rename_total_venta_kilos_total_venta_monto_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio_sugerido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio sugerido de venta",
                max_digits=12,
                null=True,
            ),
        ),
    ]
