# Generated by Django 4.2.27 on 2025-12-24 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_producto_precio_sugerido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Importacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Contenedor Tianjin Sep-2025",
                        max_length=200,
                    ),
                ),
                (
                    "kilos_ingresados",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "costo_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo total CIF + gastos asociados",
                        max_digits=14,
                    ),
                ),
                (
                    "costo_por_kg",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "kilos_restantes",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
