# Generated by Django 4.2.27 on 2025-12-24 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_importacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoOperacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arriendo", "Arriendo"),
                            ("bencina", "Bencina"),
                            ("transporte", "Transporte / despacho"),
                            ("servicios", "Servicios"),
                            ("contador", "Contador"),
                            ("marketing", "Marketing"),
                            ("insumos", "Insumos"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "monto_neto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monto NETO (SIN IVA)",
                        max_digits=12,
                    ),
                ),
                ("aplica_iva", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="importacion",
            name="costo_total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Costo total CIF + gastos asociados (SIN IVA)",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="importacion",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_sugerido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio sugerido de venta (opcional).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="numero_documento",
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
