# Generated by Django 4.2.27 on 2025-12-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_gastooperacional_alter_importacion_costo_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacion",
            name="bolsas_20_ingresadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importacion",
            name="bolsas_20_restantes",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="importacion",
            name="bolsas_8_ingresadas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importacion",
            name="bolsas_8_restantes",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
