# Generated by Django 4.2.27 on 2025-12-25 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_importacion_bolsas_20_ingresadas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MermaBolsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "tipo_bolsa",
                    models.CharField(
                        choices=[("b8", "Bolsa 8 kg"), ("b20", "Bolsa 20 kg")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("rotura", "Rotura"),
                            ("humedad", "Humedad"),
                            ("perdida", "Pérdida / extravío"),
                            ("muestra", "Muestra / regalo"),
                            ("error", "Error de inventario"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("observacion", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mermas",
                        to="crm.importacion",
                    ),
                ),
            ],
        ),
    ]
