# Generated by Django 4.2.27 on 2025-12-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_mermabolsa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importacion",
            name="bolsas_20_ingresadas",
        ),
        migrations.RemoveField(
            model_name="importacion",
            name="bolsas_20_restantes",
        ),
        migrations.RemoveField(
            model_name="importacion",
            name="bolsas_8_ingresadas",
        ),
        migrations.RemoveField(
            model_name="importacion",
            name="bolsas_8_restantes",
        ),
        migrations.AddField(
            model_name="importacion",
            name="merma_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Merma total en kilos (roturas, humedad, etc.)",
                max_digits=12,
            ),
        ),
        migrations.DeleteModel(
            name="MermaBolsa",
        ),
    ]
