# Generated by Django 4.2.27 on 2026-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_remove_importacion_bolsas_20_ingresadas_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="gastooperacional",
            options={
                "verbose_name": "Gasto Operacional",
                "verbose_name_plural": "Gastos Operacionales",
            },
        ),
        migrations.AlterModelOptions(
            name="importacion",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Importación",
                "verbose_name_plural": "Importaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AlterModelOptions(
            name="ventaitem",
            options={
                "verbose_name": "Item de Venta",
                "verbose_name_plural": "Items de Venta",
            },
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["telefono"], name="crm_cliente_telefon_8308f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["email"], name="crm_cliente_email_3bea01_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["nombre"], name="crm_cliente_nombre_a17ef0_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["-creado_en"], name="crm_cliente_creado__140eeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gastooperacional",
            index=models.Index(fields=["-fecha"], name="crm_gastoop_fecha_5ec0b4_idx"),
        ),
        migrations.AddIndex(
            model_name="gastooperacional",
            index=models.Index(
                fields=["tipo", "fecha"], name="crm_gastoop_tipo_7d33ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gastooperacional",
            index=models.Index(fields=["fecha"], name="crm_gastoop_fecha_703eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="importacion",
            index=models.Index(
                fields=["activo", "-fecha"], name="crm_importa_activo_dfdc21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["sku"], name="crm_product_sku_d580e0_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["activo", "nombre"], name="crm_product_activo_2930a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["-fecha", "cliente"], name="crm_venta_fecha_501887_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["tipo_documento", "fecha"], name="crm_venta_tipo_do_db421e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["-fecha"], name="crm_venta_fecha_d96a39_idx"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["cliente", "-fecha"], name="crm_venta_cliente_25f676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ventaitem",
            index=models.Index(
                fields=["venta", "producto"], name="crm_ventait_venta_i_74c3bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ventaitem",
            index=models.Index(
                fields=["producto"], name="crm_ventait_product_f1806f_idx"
            ),
        ),
    ]
