# Generated by Django 4.2.27 on 2026-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rutas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puntoentrega",
            options={
                "verbose_name": "Punto de Entrega",
                "verbose_name_plural": "Puntos de Entrega",
            },
        ),
        migrations.AddIndex(
            model_name="puntoentrega",
            index=models.Index(
                fields=["orden_optimo"], name="rutas_punto_orden_o_f311f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="puntoentrega",
            index=models.Index(fields=["nombre"], name="rutas_punto_nombre_d62508_idx"),
        ),
    ]
